# Generated by Django 6.0.3 on 2026-03-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.CharField(max_length=50)),
                ('is_booked', models.BooleanField(default=False)),
                ('booked_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
