# Generated by Django 6.0.3 on 2026-03-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
            ],
            options={
                'unique_together': {('date', 'time_slot')},
            },
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
